let TODO = [
    {
        "album":"",
        "albumThumb": "",
        "albumFullImg": "",
        "artist":"",
        "genre":"",
        "releaseDate":"",
        "trackList":[
           {
              "trackOne":"",
              "length":""
           },
           {
              "trackTwo":"",
              "length":""
           },
           {
              "trackThree":"",
              "length":""
           },
           {
              "trackFour":"",
              "length":""
           },
           {
              "trackFive":"",
              "length":""
           },
           {
              "trackSix":"",
              "length":""
           },
           {
              "trackSeven":"",
              "length":""
           },
           {
              "trackEight":"",
              "length":""
           },
           {
              "trackNine":"",
              "length":""
           },
           {
              "trackTen":"",
              "length":""
           }
        ]
     },
     {
        "album":"",
        "albumThumb": "",
        "albumFullImg": "",
        "artist":"",
        "genre":"",
        "releaseDate":"",
        "trackList":[
           {
              "trackOne":"",
              "length":""
           },
           {
              "trackTwo":"",
              "length":""
           },
           {
              "trackThree":"",
              "length":""
           },
           {
              "trackFour":"",
              "length":""
           },
           {
              "trackFive":"",
              "length":""
           },
           {
              "trackSix":"",
              "length":""
           },
           {
              "trackSeven":"",
              "length":""
           },
           {
              "trackEight":"",
              "length":""
           },
           {
              "trackNine":"",
              "length":""
           },
           {
              "trackTen":"",
              "length":""
           }
        ]
     },
     {
        "album":"",
        "albumThumb": "",
        "albumFullImg": "",
        "artist":"",
        "genre":"",
        "releaseDate":"",
        "trackList":[
           {
              "trackOne":"",
              "length":""
           },
           {
              "trackTwo":"",
              "length":""
           },
           {
              "trackThree":"",
              "length":""
           },
           {
              "trackFour":"",
              "length":""
           },
           {
              "trackFive":"",
              "length":""
           },
           {
              "trackSix":"",
              "length":""
           },
           {
              "trackSeven":"",
              "length":""
           },
           {
              "trackEight":"",
              "length":""
           },
           {
              "trackNine":"",
              "length":""
           },
           {
              "trackTen":"",
              "length":""
           }
        ]
     },
     {
        "album":"",
        "albumThumb": "",
        "albumFullImg": "",
        "artist":"",
        "genre":"",
        "releaseDate":"",
        "trackList":[
           {
              "trackOne":"",
              "length":""
           },
           {
              "trackTwo":"",
              "length":""
           },
           {
              "trackThree":"",
              "length":""
           },
           {
              "trackFour":"",
              "length":""
           },
           {
              "trackFive":"",
              "length":""
           },
           {
              "trackSix":"",
              "length":""
           },
           {
              "trackSeven":"",
              "length":""
           },
           {
              "trackEight":"",
              "length":""
           },
           {
              "trackNine":"",
              "length":""
           },
           {
              "trackTen":"",
              "length":""
           }
        ]
     },
     {
        "album":"",
        "albumThumb": "",
        "albumFullImg": "",
        "artist":"",
        "genre":"",
        "releaseDate":"",
        "trackList":[
           {
              "trackOne":"",
              "length":""
           },
           {
              "trackTwo":"",
              "length":""
           },
           {
              "trackThree":"",
              "length":""
           },
           {
              "trackFour":"",
              "length":""
           },
           {
              "trackFive":"",
              "length":""
           },
           {
              "trackSix":"",
              "length":""
           },
           {
              "trackSeven":"",
              "length":""
           },
           {
              "trackEight":"",
              "length":""
           },
           {
              "trackNine":"",
              "length":""
           },
           {
              "trackTen":"",
              "length":""
           }
        ]
     },
     {
        "album":"",
        "albumThumb": "",
        "albumFullImg": "",
        "artist":"",
        "genre":"",
        "releaseDate":"",
        "trackList":[
           {
              "trackOne":"",
              "length":""
           },
           {
              "trackTwo":"",
              "length":""
           },
           {
              "trackThree":"",
              "length":""
           },
           {
              "trackFour":"",
              "length":""
           },
           {
              "trackFive":"",
              "length":""
           },
           {
              "trackSix":"",
              "length":""
           },
           {
              "trackSeven":"",
              "length":""
           },
           {
              "trackEight":"",
              "length":""
           },
           {
              "trackNine":"",
              "length":""
           },
           {
              "trackTen":"",
              "length":""
           }
        ]
     },
     {
        "album":"",
        "albumThumb": "",
        "albumFullImg": "",
        "artist":"",
        "genre":"",
        "releaseDate":"",
        "trackList":[
           {
              "trackOne":"",
              "length":""
           },
           {
              "trackTwo":"",
              "length":""
           },
           {
              "trackThree":"",
              "length":""
           },
           {
              "trackFour":"",
              "length":""
           },
           {
              "trackFive":"",
              "length":""
           },
           {
              "trackSix":"",
              "length":""
           },
           {
              "trackSeven":"",
              "length":""
           },
           {
              "trackEight":"",
              "length":""
           },
           {
              "trackNine":"",
              "length":""
           },
           {
              "trackTen":"",
              "length":""
           }
        ]
     },
     {
        "album":"",
        "albumThumb": "",
        "albumFullImg": "",
        "artist":"",
        "genre":"",
        "releaseDate":"",
        "trackList":[
           {
              "trackOne":"",
              "length":""
           },
           {
              "trackTwo":"",
              "length":""
           },
           {
              "trackThree":"",
              "length":""
           },
           {
              "trackFour":"",
              "length":""
           },
           {
              "trackFive":"",
              "length":""
           },
           {
              "trackSix":"",
              "length":""
           },
           {
              "trackSeven":"",
              "length":""
           },
           {
              "trackEight":"",
              "length":""
           },
           {
              "trackNine":"",
              "length":""
           },
           {
              "trackTen":"",
              "length":""
           }
        ]
     },
     {
        "album":"",
        "albumThumb": "",
        "albumFullImg": "",
        "artist":"",
        "genre":"",
        "releaseDate":"",
        "trackList":[
           {
              "trackOne":"",
              "length":""
           },
           {
              "trackTwo":"",
              "length":""
           },
           {
              "trackThree":"",
              "length":""
           },
           {
              "trackFour":"",
              "length":""
           },
           {
              "trackFive":"",
              "length":""
           },
           {
              "trackSix":"",
              "length":""
           },
           {
              "trackSeven":"",
              "length":""
           },
           {
              "trackEight":"",
              "length":""
           },
           {
              "trackNine":"",
              "length":""
           },
           {
              "trackTen":"",
              "length":""
           }
        ]
     },
     {
        "album":"",
        "albumThumb": "",
        "albumFullImg": "",
        "artist":"",
        "genre":"",
        "releaseDate":"",
        "trackList":[
           {
              "trackOne":"",
              "length":""
           },
           {
              "trackTwo":"",
              "length":""
           },
           {
              "trackThree":"",
              "length":""
           },
           {
              "trackFour":"",
              "length":""
           },
           {
              "trackFive":"",
              "length":""
           },
           {
              "trackSix":"",
              "length":""
           },
           {
              "trackSeven":"",
              "length":""
           },
           {
              "trackEight":"",
              "length":""
           },
           {
              "trackNine":"",
              "length":""
           },
           {
              "trackTen":"",
              "length":""
           }
        ]
     }
 ];